name: Deploy OSINT course to Azure Static Web Apps

on:
  push:
    branches: [main]
    paths:
      - 'osint/**'
  pull_request:
    branches: [main]
    paths:
      - 'osint/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_OSINT }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: /osint
          api_location: /osint/api
          output_location: build
